name: grounded
description: "Grounded Habit Trackker."

publish_to: 'none' 


environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  flutter_svg:
  google_fonts:
  shared_preferences:
  provider:
  clipboard: 
  awesome_notifications:
  permission_handler:
  firebase_messaging:
  flutter_contacts:
  

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons:



flutter:


  uses-material-design: true

  assets:
    - assets/icon/app_icon.png
    - assets/logos/google-icon.png




flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#214E34"
  adaptive_icon_foreground: "assets/icon/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_foreground_scale: 0.8   # ðŸ‘ˆ shrink a bit (0.7â€“0.9 works)


